import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const FF_LIST_PROJECTS = "https://api.flutterflow.io/v2/l/listProjects";
const MAX_BODY = 16 * 1024;

function text(body: string, status = 200) {
  return new Response(body, {
    status,
    headers: {
      "Content-Type": "text/plain; charset=UTF-8",
      "Cache-Control": "no-store, max-age=0",
      "Pragma": "no-cache",
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "no-referrer",
    },
  });
}

async function sha256Hex(input: string) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}
function normalizeName(s: unknown) { return String(s ?? "").toLowerCase().replace(/[^a-z0-9]+/g, ""); }

Deno.serve(async (req: Request) => {
  if (req.method === "GET") {
    return text("This endpoint accepts the secure FlutterFlow credential form generated by ChatGPT. Return to ChatGPT and open the provided HTML form.", 200);
  }
  if (req.method !== "POST") return text("Method not allowed.", 405);

  const length = Number(req.headers.get("content-length") || "0");
  if (length > MAX_BODY) return text("Request too large. No credential was stored.", 413);

  let form: FormData;
  try { form = await req.formData(); } catch { return text("Invalid request. No credential was stored.", 400); }
  const code = String(form.get("code") || "").trim();
  const token = String(form.get("token") || "").trim();
  if (code.length < 32 || token.length < 20) return text("Invalid input. No credential was stored.", 400);

  const codeSha = await sha256Hex(code);
  let ffResp: Response;
  try {
    ffResp = await fetch(FF_LIST_PROJECTS, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", Accept: "application/json" },
      body: JSON.stringify({ project_type: "ALL", deserialize_response: true }),
      cache: "no-store",
    });
  } catch {
    return text("FlutterFlow could not be reached. No credential was stored. Try again later.", 502);
  }

  const payload = await ffResp.json().catch(() => null);
  if (!ffResp.ok || !payload?.success) {
    return text("FlutterFlow did not accept this token. No credential was stored. Create a current API token in FlutterFlow and try again.", 401);
  }

  const entries = Array.isArray(payload?.value?.entries) ? payload.value.entries : [];
  const match = entries.find((entry: any) => {
    const n = normalizeName(entry?.project?.name);
    return n === "pandorasbox" || n === "pandorabox";
  });
  if (!match?.id) {
    return text("The token is valid, but the existing Pandoras Box project was not found. No credential was stored. Use the FlutterFlow account that owns or can edit that project.", 409);
  }

  const { data, error } = await admin.rpc("consume_flutterflow_credential_handoff", {
    p_code_sha256: codeSha,
    p_token: token,
    p_project_id: String(match.id),
    p_project_name: String(match?.project?.name || "Pandoras Box"),
  });
  if (error || data !== true) {
    return text("This secure link is expired or already used. No new credential was stored. Return to ChatGPT for a fresh form.", 410);
  }

  return text(`CONNECTED\n\nFlutterFlow verified the existing ${String(match?.project?.name || "Pandoras Box")} project. The token is stored privately in Supabase Vault.\n\nReturn to ChatGPT and say: Go`, 200);
});
